language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

install:
  - travis_retry ./bin/composer.phar install --no-interaction --prefer-source

after_script:
  - travis_retry wget https://scrutinizer-ci.com/ocular.phar
  - travis_retry bash -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.xml; fi;'

after_script:
  - travis_retry wget https://scrutinizer-ci.com/ocular.phar
  - travis_retry bash -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.xml; fi;'
