language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - nightly

sudo: false

before_script:
  - rm composer.lock
  - composer install --no-interaction # --prefer-source

script:
  - vendor/bin/atoum

after_script:
  - travis_retry wget https://scrutinizer-ci.com/ocular.phar
  - travis_retry bash -c 'php ocular.phar code-coverage:upload --format=php-clover tests/reports/clover.xml'
